#! /usr/bin/env perl

# Converts the Makefile buildtargets to a cmake format.
# ./cmakify_buildtarget.pl < Makefile > cmake/buildtarget.cmake

$in_build_target = 0;

print("# This file was automatically generated by cmakify_buildtarget.pl.\n");
print("\n");

while(<>) {
    chomp;
    # Find lines like:
    #     cray: # BUILDTARGET Cray Programming Environment
    if(/^(\S+):(\s*#.*$)?/) {
        $buildtarget = $1; # like "cray"
        if($in_build_target) {
            print("elseif(BUILDTARGET STREQUAL \"$buildtarget\")$2\n")
        } else {
            print("if(BUILDTARGET STREQUAL \"$buildtarget\")$2\n")
        }
        $in_build_target = 1;
        print("  message(\"Using compiliation options for build target \\\"$buildtarget\\\"\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_Fortran_FLAGS_RELEASE \"\${CMAKE_Fortran_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"CFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_C_FLAGS_RELEASE \"\${CMAKE_C_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"CXXFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_CXX_FLAGS_RELEASE \"\${CMAKE_CXX_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_Fortran_FLAGS_DEBUG \"\${CMAKE_Fortran_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"CFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_C_FLAGS_DEBUG \"\${CMAKE_C_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"CXXFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_CXX_FLAGS_DEBUG \"\${CMAKE_CXX_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_PROMOTION\s*=\s*(.*?)"/) {
        print("  if(MPAS_PRECISION STREQUAL double)\n");
        print("    set(CMAKE_Fortran_FLAGS_RELEASE \"\${CMAKE_Fortran_FLAGS_RELEASE} $1\")\n");
        print("    set(CMAKE_Fortran_FLAGS_DEBUG \"\${CMAKE_Fortran_FLAGS_DEBUG} $1\")\n");
        print("  endif()\n");


    } elsif(/^\S.*=/ and $in_build_target) {
        # End of BUILDTARGET list.
        print("else()\n");
        print("  # Maybe this should be a SEND_ERROR?\n");
        print("  message( WARNING \"Unrecognized BUILDTARGET \${BUILDTARGET}. Will use default options.\" )\n");
        print("endif()\n");
        last;
    }
}
