set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -convert big_endian -free -align array64byte")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -g -convert big_endian -free -check all -fpe0 -traceback")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -g -traceback")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g -traceback")
if(MPAS_DOUBLE_PRECISION)
  # cmake doesn't correctly detect the flag for double precision reals on ifort
  set(CMAKE_Fortran_FLAGS_RELEASE "$CMAKE_Fortran_FLAGS_RELEASE -real-size 64")
  set(CMAKE_Fortran_FLAGS_DEBUG "$CMAKE_Fortran_FLAGS_RELEASE -real-size 64")
endif()
